project:
  type: website

execute:
  freeze: auto

website:
  title: "Origins"
  site-url: https://origins.palaeobiology.org
  description: "Origins website"
  image: "images/dinosaur-extinction.png"
  favicon: "assets/favicon.png"
  open-graph:
    image: "images/dinosaur-extinction.png"
    image-width: 500
    image-height: 500
    locale: en-GB
  twitter-card:
    title: Lewis A. Jones
    description: "Origins website"
    image: "images/dinosaur-extinction.png"
    image-width: 500
    image-height: 500
    card-style: summary
    creator: "@LewisAlanJones"
    site: "@LewisAlanJones"
  navbar:
    title: false
    foreground: "black"
    background: "transparent"
    search: false
    right:
      - text: "Origins"
        file: index.qmd
      - icon: twitter
        href: "https://twitter.com/LewisAlanJones"
      - icon: github
        href: "https://github.com/LewisAJones"
      - icon: envelope-fill
        href: "mailto:LewisA.Jones@outlook.com"
  page-footer:
    border: false
    background: "#a2247c"
    left: "Copyright 2023, Lewis A. Jones"
    right:
      - icon: github
        href: https://github.com/LewisAJones
      - icon: twitter
        href: https://twitter.com/LewisAlanJones

format:
  html:
    theme: style.scss
    css: style.scss
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source

