project:
  type: website

execute:
  freeze: auto

website:
  title: "Origins"
  site-url: https://origins.palaeobiology.org
  description: "Origins website"
  image: "images/dinosaur-extinction.png"
  favicon: "assets/favicon.png"
  search: false
  open-graph:
    image: "images/dinosaur-extinction.png"
    image-width: 500
    image-height: 500
    locale: en-GB
  twitter-card:
    title: Lewis A. Jones
    description: "Origins website"
    image: "images/dinosaur-extinction.png"
    image-width: 500
    image-height: 500
    card-style: summary
    creator: "@LewisAlanJones"
    site: "@LewisAlanJones"
  navbar:
    title: false
    collapse: false
    foreground: "black"
    background: "transparent"
    right:
      - text: "Contribute"
        href: "https://forms.gle/42fqXep3b8pf8KMk8"
        target: "_blank"
      - icon: twitter
        href: "https://twitter.com/MirantaKouvari"
        target: "_blank"
      - icon: twitter
        href: "https://twitter.com/LewisAlanJones"
        target: "_blank"
      - icon: cup-fill
        href: "https://bmc.link/origins"
        target: "_blank"
      - icon: envelope-fill
        href: "mailto:LewisA.Jones@outlook.com"
  page-footer:
    border: false
    background: "#a2247c"
    left: "Copyright 2023, Lewis A. Jones & Miranta Kouvari"
    right:
      - text: "Contribute"
        href: "https://forms.gle/42fqXep3b8pf8KMk8"
        target: "_blank"
      - icon: twitter
        href: "https://twitter.com/MirantaKouvari"
        target: "_blank"
      - icon: twitter
        href: "https://twitter.com/LewisAlanJones"
        target: "_blank"
      - icon: cup-fill
        href: "https://bmc.link/origins"
        target: "_blank"
      - icon: envelope-fill
        href: "mailto:LewisA.Jones@outlook.com"

format:
  html:
    theme: style.scss
    css: style.scss
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source

