project:
  type: website

website:
  title: "Origins"
  site-url: https://origins.palaeobiology.org
  description: "Scroll through Earth's History"
  image: "images/dinosaur-extinction.png"
  favicon: "assets/favicon.png"
  search: false
  open-graph:
    image: "images/dinosaur-extinction.png"
    image-width: 500
    image-height: 500
    locale: en-GB
  twitter-card:
    title: "Origins"
    description: "Scroll through Earth's History"
    image: "images/dinosaur-extinction.png"
    image-width: 500
    image-height: 500
    card-style: summary_large_image
    creator: "@LewisAlanJones"
    site: "@LewisAlanJones"
  navbar:
    title: Origins
    collapse: true
    foreground: "black"
    background: "transparent"
    right:
      - text: "Contribute"
        href: "https://forms.gle/42fqXep3b8pf8KMk8"
        target: "_blank"

format:
  html:
    css: style.scss
    toc: false
    smooth-scroll: false
    link-external-newwindow: true

editor: source

